[versions]
minSdk = "26"
compileSdk = "36"
targetSdk = "36"

agp = "8.12.3"
kotlin = "2.3.0"
ksp = "2.3.5"

material = "1.13.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
constraintLayout = "2.2.1"
recycleview = "1.4.0"
lifecycle = "2.10.0"
activityKtx = "1.12.3"
fragmentKtx = "1.8.9"
navigation = "2.9.7"
datastore = "1.2.0"
viewpager2 = "1.1.0"
preference = "1.2.1"
splashscreen = "1.2.0"
room = "2.8.4"
imageCropper = "4.5.0"
koin = "3.5.6"
kotlinxCoroutine = "1.10.1"
navSafeArgs = "2.9.7"
kotlinxDatetime = "0.7.1"


[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

recycleview = { module = "androidx.recyclerview:recyclerview", version.ref = "recycleview" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }

lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }

activity = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }

nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }

datastore-preference-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
datastore-preference = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

android-image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "imageCropper" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutine" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutine" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-navigation = { module = "io.insert-koin:koin-androidx-navigation", version.ref = "koin" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
nav-safe-args = { id = "androidx.navigation.safeargs", version.ref = "navSafeArgs" }
com-android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }


[bundles]
commoncore = [
    "core-ktx",
    "appcompat",
    "appcompat-resources",
    "material"
]

coroutines = [
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-core",
]

room = [
    "room-runtime",
    "room-ktx",
]

lifecycle = [
    "lifecycle-livedata",
    "lifecycle-viewmodel",
    "lifecycle-common-java8",
]

activityfragment = [
    "activity",
    "fragment",
]

navcomponent = [
    "nav-ui",
    "nav-fragment",
]

datastore = [
    "datastore-preference-core",
    "datastore-preference",
]

koin = [
    "koin-core",
    "koin-android",
    "koin-androidx-navigation",
]
